- src/json-validator.cpp
Hi, thanks for making this library!
On my platform I was getting a handful of errors like this:
```
json-validator.cpp:677:31: error: use of overloaded operator '<' is ambiguous (with operand types 'std::size_t'
(aka 'unsigned long') and 'const nlohmann::basic_json<std::map, std::vector, std::__1::basic_string<char>, bool, long long, unsigned long long,
double, std::allocator, adl_serializer>')
if (utf8_length( instance ) < attr.value()) {
```
which I fixed by using explicit `.get<type>()` to disambiguate the json values.
FYI here's the compiler info:
```
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
```
and I compile using the `-std=c++11` flag.
> use explicit json.get<type>() to avoid compiler ambiguity errors

- src/json-validator.cpp
If the schema has
```
type: ["string", "number"]
```
and the corresponding value in the json document is an integer,  I was getting an error:
```integer is not any of ["string","number"] for ...```
Fixed in this PR.
> Bug fix: Accept integer as a number in a list of types

- src/json-schema.hpp
- src/json-validator.cpp
In my app I have a `const json` object, which I wanted to validate.
The validator doesn't try to mutate the json document, so it was easy enough to add `const` to the declaration and propagate it as needed.
> Have validate() take a const json reference.

- CMakeLists.txt
- app/json-schema-validate.cpp
- src/json-schema.hpp
- src/json-validator.cpp
I have added preprocessor code to allow exporting the symbols from DLLs, conditionally disabled -Wextra and -Wall in case of Visual Studio compiler, and fixed two warnings.  After those changes, the only MSVC warning remaining is C4251 (https://msdn.microsoft.com/en-us/library/esew7y1w.aspx).  The subject of this issue is probably not a problem when building json-schema-validator and the code that uses it with the very same compiler.  Otherwise, it is flagging a potential problem, so this warning should probably not be suppressed.
> Build as shared library on Windows using Visual Studio compiler

- src/json-validator.cpp
The error message for "minItems" was the same as "maxItems". Change it to use the same verbiage as "minProperties".
> Change error message for "minItems".

- README.md
Make the example in the README.md more useful because it can be run directly and demonstrates some useful features of the library.
Removes the loader callback, which was VERY unclear to new users and doesn't seem strictly required.
See also #18
> Add a runnable and useful example

- src/json-validator.cpp
Pleased to see the rewrite, as we've found things like repeated [recompiling of regex patterns in v1.0.0](https://github.com/pboettch/json-schema-validator/blob/1.0.0/src/json-validator.cpp#L694-L700), etc. to be a potential performance problem.
I've only just started playing with the rewrite, but I thought I'd immediately track things I found while trying to upgrade.
Four commits so far:
1. One missing #include
2. Backwards incompatibility - json_validator used to be copyable, it now wasn't even movable, so this commit fixes that
3. Delete whitespace either side of the '#' which indicates fragment identifier between the URI and json-pointer or local name (i.e. from a $id)
4. Update test for 3.
I'm seeing an exception from within test/id-ref.cpp:
```
[json.exception.parse_error.107] parse …
```
> first experiment with upgrading from v1.0.0

- app/json-schema-validate.cpp
Some build and test systems offer only read-only file system, so open JSON and schema files in read-only mode (since we anyhow don't want to write into them).
(Additionally, catch exceptions with `const` qualifiers, if I was already there.)
> Open files in read-only mode in validator

- README.md
Code example in README.md does not compile.
First argument of basic_error_handler::error is json_pointer instead of std::string.
> Fix non-compilable code example in README.md

- src/json-validator.cpp
- src/nlohmann/json-schema.hpp
If a json object containing a schema is moved into the json validator it
should not be copied. At least the public interface of the validator
class schould not force the copy.
> Avoid copy of json on set_root_schema

- src/json-validator.cpp
- test/CMakeLists.txt
- test/issue-117-format-error.cpp
Now if you use schema with `format` field and don't set format checker, then you get error about not provided `format checker` at validation time. But what about verify existence of `format checker` at schema parsing time? I think it will be more useful
> add checking about format-checker existance at schema parsing time

- CMakeLists.txt
Similarly to how installation is disabled when included via ``add_subdirectory``, I believe test and example building should be disabled as well.
It seems that CMake does not make it possible to set options only for a sub-project without affecting the parent project. An alternative to this PR would be to rename ``BUILD_TESTS`` and ``BUILD_EXAMPLES`` to be globally unique so they can be set in the parent.
> Disable tests and examples when used via add_subdirectory

- src/json-validator.cpp
- test/issue-25-default-values.cpp
Hello,
This fix resolve a issue we faced with empty object as default value. Previous behavior of null as default value is the same (is_empty on a null json return true).
Here is a example of new behavior:
Schema:
```
{
"$schema": "http://json-schema.org/draft-07/schema#",
"title": "A person",
"properties": {
"address":{
"type": "object",
"default": {}
}
},
"type": "object"
}
```
Object:
`{}`
Patch:
```
[{"op":"add","path":"/address","value":{}}]
```
Object after applying patch:
```
{
"address": {}
}
```
> fix default is empty object

- CMakeLists.txt
- nlohmann_json_schema_validatorConfig.cmake.in
Fixes #127 
- Add relative paths to cmake generated package configs
- Add nlohmann json 3.8. requirement to package config
Tested native and on cross-compile toolchain
> re-worked install configs

- .travis.yml
- CMakeLists.txt
This is a follow up to PR #121. It fixes the integration, adds travis tests using Hunter package manager to retrieve nlohmann json library. 
It also includes the MSVC fix.
Branch was rebased to master and commits squashed.
> Fixed Hunter integration and added tests

- src/nlohmann/json-schema.hpp
Thanks for the great library :)
The call to std::tie was causing a compiler error on MSVC 2017:
```
json-schema.hpp(64): error C2664: 'std::tuple<const std::string &,const std::string &,const std::string &,const std::string &,std::string &> std::tie<const std::string,const std::string,const std::string,const std::string,std::string>(const std::string &,const std::string &,const std::string &,const std::string &,std::string &) noexcept': cannot convert argument 5 from 'std::string' to 'std::string &'
json-schema.hpp(65): note: A non-const reference may only be bound to an lvalue
```
I was able to reduce the problem to the following code snippet that [compiles on gcc/clang](https://wandbox.org/permlink/Vg5b71MshLatmtVz), but fails to compile on MSVC 2017:
```
#include <string>
#include …
```
> Remove unnecessary call to std::tie (fixes compilation error on MSVC 2017)

- src/nlohmann/json-schema.hpp
Apparently, [my fix for MSVC 2017](https://github.com/pboettch/json-schema-validator/pull/137) has broken compilation on pre-[N4387](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4387.html) `std::tuple` implementations. This is currently noticeable in the CI build status, where compilation fails on both gcc-4.9 and gcc-5. 
In this PR, I switched to using `std::make_tuple` instead of list initialization. This avoids relying on the presence of a viable non-explicit constructor in `std::tuple`, making the code valid for old C++11 `std::tuple` implementations as well.
Sorry, I just learned about this paper when I saw the "build failing" CI label in the project README.
Thanks again!
> Fix explicit tuple constructor error on gcc-5

- src/json-uri.cpp
- src/json-validator.cpp
Hi!
We are using your validator but use more warnings than you do. In case you're interested, here I changed all casts (to uint8_t) to explicit static_casts and added a cast here:
```
-		double eps = std::nextafter(x, 0) - x;
+		double eps = std::nextafter(x, 0) - static_cast<double>(x);
```
In case you're not interested, please let me know.
By the way:
The validation library actually builds with the following warnings after these changes, although the tests do not (which may be due to nlohmann/json tests not building with these)
```
-Werror -Wconversion -pedantic-errors -pedantic -Wall -Wextra -Wcast-align -Wcast-qual -Wctor-dtor-privacy
-Wdisabled-optimization -Wformat=2 -Winit-self -Wmissing-declarations -Wmissing-include-dirs -Wold-style-cast 
-Woverloaded-virtual -Wredundant-decls …
```
> fixed occurences of old-style casts and an implicit cast to double

- src/json-validator.cpp
As detailed in https://github.com/nlohmann/json#implicit-conversions, it's recommended not to use implicit conversions from json. This change allows those using "JSON_ImplicitConversions" OFF in the nlohmann::json package to build this package without errors.
> Use explicit type conversion from json

- src/json-validator.cpp
The error messages for exclusive minimum and maximum have been updated
to include 'or equals' for greater clarity.
> Updated exclusive min/max error message #182

- src/nlohmann/json-schema.hpp
Seems like this macro was missing leading to linker errors on windows when linking dynamically
> Add dll export macro to format check

- src/json-validator.cpp
Fixes https://github.com/pboettch/json-schema-validator/issues/198
Should also be backward compatible with nlohmann::json <3.11
> Fix explicit conversion to string

- .github/workflows/github-actions.yml
- src/json-validator.cpp
- src/nlohmann/json-schema.hpp
- test/binary-validation.cpp
- test/uri.cpp
Hi @pboettch, PTAL.
This updates CI to run on main and uses the latest nlohmann-json to test.
This also adds the `to_string()` call to remove warnings.
The current tag is also very old so could we get an updated tag?
> Update CI and fix warnings

- src/json-patch.cpp
More warnings missed in #214 .
> chore: use to_string() for json_pointers

- CMakeLists.txt
Due to the install step we are unable to use fetch content without installing nlohmann/json.
With this fix we can simply turn off the install prior to declaring json schema and cmake will not error out
See example
```
cmake_minimum_required(VERSION 3.13)
project(example)
include(FetchContent)
FetchContent_Declare(nlohmann_json URL https://github.com/nlohmann/json/releases/download/v3.11.2/json.tar.xz)
FetchContent_MakeAvailable(nlohmann_json)
FetchContent_Declare(
json_schema 
GIT_REPOSITORY https://github.com/pboettch/json-schema-validator.git 
GIT_TAG main)
FetchContent_MakeAvailable(json_schema)
add_subdirectory(src)
```
> cmake: add option to disable installing targets

- .github/workflows/github-actions.yml
- conanfile.py
Adds updates to `conanfile.py` as the existing was not working anymore. 
Summary:
- Updates dependency `nlohmann_json` to v3.11.2
- Updates handling of dependency
Verified using Conan version 1.52.0 :
1. Building in repo
```
mkdir build && cd build
conan install ..
conan build ..
```
Minor remark: the test-case `cmake-install` does not work with this method. All other tests work as expected by invocation of `ctest -V`.
1. Creating package in conan cache
```
conan create .
```
> Updates conanfile.py

- nlohmann_json_schema_validatorConfig.cmake.in
This applies the vcpkg patch that replaces the direct call to `find_package` with the `find_dependency` macro.
Note that this macro does not implicitly specify a version. Like the main `CMakeLists.txt` file i've omitted it to avoid tying the config file to a specific version.
See pboettch/json-schema-validator#207
> Use find_dependency in PackageConfig file

- CMakeLists.txt
Resolves pboettch/json-schema-validator#195
This initializes the options to the detected default, but still allows the user to override it freely.
> Make JSON_VALIDATOR_BUILD_EXAMPLES and JSON_VALIDATOR_BUILD_TESTS overridable by user

- src/string-format-check.cpp
This makes _string-format-check.cpp_ consistent with _smtp-address-validator.cpp_.
This means that the _nlohmann_ directory itself doesn't have to be in the system search path. (The directory in which the _nlohmann_ directory is contained is much more likely to be, so e.g. `#include <nlohmann/json-schema.hpp>` is fine.)
> Local include for smtp-address-validator.hpp

- src/smtp-address-validator.cpp
The code assumes that char is signed, but whether char is signed or unsigned is implementation defined. On some architectures like PowerPC, GCC treats char as unsigned resulting in compile errors:
smtp-address-validator.cpp:213:1: error: narrowing conversion of '-32' from 'int' to 'char' [-Wnarrowing]
Fix this by specifying signed char.
> Fix assumed signed char

- src/json-validator.cpp
- test/CMakeLists.txt
- test/issue-243-root-default-values.cpp
Fix for #243 that creates a patch on `null` json data in case the schema defines a default value at root.
> Create path with root defaults

- CMakeLists.txt
During the configuring of json-schema-validator, the repository nlohmann_json is fetched via the fetch_content functionality of CMake. It is a huge repository with size 180MB, which are downloaded whenever one configures CMake on an empty build directory (e.g. after deleting the build directory to clear out cached CMake variables.) The repository
https://github.com/ArthurSonzogni/nlohmann_json_cmake_fetchcontent
only contains releases instead of all development commits and has (at the moment) size of only 830kB, which stronly cuts the download time.
This PR implements https://github.com/pboettch/json-schema-validator/issues/277.
> Replace the full nlohmann_json repo with a fetch_content variant.

- src/smtp-address-validator.cpp
Fixes #283
smtp-address-validator.cpp was originally generated using Ragel and that left refences (in "#line" form) to non-existent smtp-address-validator.rl file which confuse gcovr. Fix this by removing all lines starting with "#line".
> Fix code coverage for smtp-address-validator.cpp

- src/string-format-check.cpp
There is code in src/json-validator.cpp that enables the Boost regex library to be used instead of the std::regex library via a cpp option.  However there is std::regex code in src/string-format-check.cpp and there is no option to use Boost regex.  This PR adds the option of using Boost regex for that file as well.
> Enable boost regex usage for string-format-check.cpp

- src/smtp-address-validator.cpp
Fix "unused variable" warnings generated by Clang.
This fix can be useful for those who want to build with -Werror
> Fix Clang compiler warnings

- src/json-patch.hpp
- src/json-validator.cpp
A recent fix to discard patch from invalid logical combination introduced a lot (for large json instance and/or schema) of copies to make a patch backup. On some case, this introduced up to a 100x slower validation time (I observed times from 50ms to 7s on one of my use case).
Resizing the patch object to its previous size avoid unnecessary temporary allocations from the backup object.
* I needed to expose the internal json object to be able to resize it. I'm not sure how differently we could achieve this if you don't like that.
* It also fixes the default value of an empty json_patch. I think it should be an empty array and not a null json according to the json patch schema.
* I know you mentioned in #229 that you won't accept more changes on this subject, however this is quite a big …
> Fix performance regression from logical combination patch discard

- CMakeLists.txt
If somebody uses json-schema-validator and nlohman/json as cmake subprojects, then there are problem with building nlohman_json twice. Instead fetch nlohman_json only if such TARGET doesn't exist
> do not fetch nlohmann_json if it already added in main project

- README.md
I currently have version 3.7.0 of NLohmann's JSON library, was unfortunately surprised to find out I can't actually use this library since the advertised required version doesn't match the actual requirement
> Update required dependency version to match actual requirement

- src/CMakeLists.txt
> Fix cmake install target on windows

- src/json-validator.cpp
- test/issue-105-verbose-combination-errors.cpp
Fix pre-commit GitHub workflow failures.
"test / Check pre-commit" workflow was failing due to source files not being formatted according to .clang-format
> Apply clang-format / fix "test / Check pre-commit" failures

- src/json-validator.cpp
One of the changes for the 1020-12 schema specification (#153) is the keyword `$defs` instead of `definitions`. This PR implements that change.
With this change in place I can load the MNX schema and correctly validate MNX files against it. However, I am a newbie here, so I welcome comments on how to improve it.
> add support for `$defs` instead of `definitions`.

- src/json-validator.cpp
Follow up for this issue:
https://github.com/pboettch/json-schema-validator/issues/333
My suggested fix in the issue was not quite right, using `contains()` is more appropriate than `find()`.
> Reference validation using contains() result rather than exception handling
